[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[window]
opacity = 1
padding.x = 0
padding.y = 0

[colors.primary]
background = "#ffffff"
foreground = "#383a42"

[colors.cursor]
text = "#ffffff"
cursor = "#383a42"

[colors.selection]
text = "#383a42"
background = "#e5e5e6"

[colors.normal]
black = "#383a42"
red = "#e45649"
green = "#50a14f"
yellow = "#c18401"
blue = "#0184bc"
magenta = "#a626a4"
cyan = "#0997b3"
white = "#909090"

[colors.bright]
black = "#383a42"
red = "#ff6b66"
green = "#87c782"
yellow = "#e4b51c"
blue = "#4cb2ff"
magenta = "#b941b9"
cyan = "#1cb0cd"
white = "#595959"

[font]
size = 11

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "None"

# Colors inspired by One Light theme while maintaining your configuration structure
# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a
# small box when a HEX is detected by the editor.
